//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSIM_VEFR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsIntialized {
            get {
                return ((bool)(this["IsIntialized"]));
            }
            set {
                this["IsIntialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSetMaxVehicles {
            get {
                return ((bool)(this["IsSetMaxVehicles"]));
            }
            set {
                this["IsSetMaxVehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MaxNumberOfVehicles {
            get {
                return ((int)(this["MaxNumberOfVehicles"]));
            }
            set {
                this["MaxNumberOfVehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double WeightConnectivity {
            get {
                return ((double)(this["WeightConnectivity"]));
            }
            set {
                this["WeightConnectivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double WeightShortestDistance {
            get {
                return ((double)(this["WeightShortestDistance"]));
            }
            set {
                this["WeightShortestDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double IntraVehiForwardDirectionPar {
            get {
                return ((double)(this["IntraVehiForwardDirectionPar"]));
            }
            set {
                this["IntraVehiForwardDirectionPar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double CommunicationRange {
            get {
                return ((double)(this["CommunicationRange"]));
            }
            set {
                this["CommunicationRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxSpeed {
            get {
                return ((double)(this["MaxSpeed"]));
            }
            set {
                this["MaxSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinSpeed {
            get {
                return ((double)(this["MinSpeed"]));
            }
            set {
                this["MinSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int NumberofPackets {
            get {
                return ((int)(this["NumberofPackets"]));
            }
            set {
                this["NumberofPackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Rows_net_top {
            get {
                return ((int)(this["Rows_net_top"]));
            }
            set {
                this["Rows_net_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Cols_net_top {
            get {
                return ((int)(this["Cols_net_top"]));
            }
            set {
                this["Cols_net_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HorizontalLength {
            get {
                return ((double)(this["HorizontalLength"]));
            }
            set {
                this["HorizontalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double VerticalLength {
            get {
                return ((double)(this["VerticalLength"]));
            }
            set {
                this["VerticalLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LaneCount_top_gen {
            get {
                return ((int)(this["LaneCount_top_gen"]));
            }
            set {
                this["LaneCount_top_gen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SliderValue {
            get {
                return ((double)(this["SliderValue"]));
            }
            set {
                this["SliderValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MaximumAttemps {
            get {
                return ((int)(this["MaximumAttemps"]));
            }
            set {
                this["MaximumAttemps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double MaxStoreTime {
            get {
                return ((double)(this["MaxStoreTime"]));
            }
            set {
                this["MaxStoreTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string NetTopName {
            get {
                return ((string)(this["NetTopName"]));
            }
            set {
                this["NetTopName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double TraficSignalingTimerInterval {
            get {
                return ((double)(this["TraficSignalingTimerInterval"]));
            }
            set {
                this["TraficSignalingTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DistanceImportance {
            get {
                return ((bool)(this["DistanceImportance"]));
            }
            set {
                this["DistanceImportance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DistanceBetweenSourceAndDestination {
            get {
                return ((double)(this["DistanceBetweenSourceAndDestination"]));
            }
            set {
                this["DistanceBetweenSourceAndDestination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double IntraVehiBackwardDirectionPar {
            get {
                return ((double)(this["IntraVehiBackwardDirectionPar"]));
            }
            set {
                this["IntraVehiBackwardDirectionPar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RandomSpeed")]
        public string AccellerationType {
            get {
                return ((string)(this["AccellerationType"]));
            }
            set {
                this["AccellerationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintIntraInfo {
            get {
                return ((bool)(this["PrintIntraInfo"]));
            }
            set {
                this["PrintIntraInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintInterInfo {
            get {
                return ((bool)(this["PrintInterInfo"]));
            }
            set {
                this["PrintInterInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PacketGeneratedType {
            get {
                return ((string)(this["PacketGeneratedType"]));
            }
            set {
                this["PacketGeneratedType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisplayInfoFlag {
            get {
                return ((string)(this["DisplayInfoFlag"]));
            }
            set {
                this["DisplayInfoFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RoutingProtocolString {
            get {
                return ((string)(this["RoutingProtocolString"]));
            }
            set {
                this["RoutingProtocolString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveVehiclesCrisp {
            get {
                return ((bool)(this["SaveVehiclesCrisp"]));
            }
            set {
                this["SaveVehiclesCrisp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveJunctionsCrisp {
            get {
                return ((bool)(this["SaveJunctionsCrisp"]));
            }
            set {
                this["SaveJunctionsCrisp"] = value;
            }
        }
    }
}
